CXX      = g++
CXXFLAGS = -Wall -I./SFML-3.0.2/include
LDFLAGS  = -L./SFML-3.0.2/lib
LIBS     = -lsfml-graphics -lsfml-window -lsfml-system -mwindows
TARGET   = paint_demo.exe
SRC      = HelloPaint.cpp
SFML_DIR = ./SFML-3.0.2

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS) $(LIBS)

run: $(TARGET)
	@if not exist sfml-graphics-3.dll (copy "$(SFML_DIR)\bin\*.dll" .) && $(TARGET)

clean:
	del /Q $(TARGET)